### ISSUE TITLE
Standard Object Text Character Parsing

### ISSUE THREAD

**Issue by mat-px** [MissouriMRR/SUAS-2022#14]
## Summary
Detect text on the standard ODLC objects and return the bounding area and alphabetic characters found

## Extended Summary
**Objective:** This task involves building a function of a text_detection module that will run in the vision pipeline that is capable of processing an image containing at least one ODLC standard object, and detecting the single-character, 1-inch-thick, alphabetic lettering on the Standard Object(s).

**Output:** The output required for this detection is the exact character of the English alphabet that is on the ODLC Standard Object as well as the bounding box of that character.

**Comment by fallscameron01** [comment]
Plan for detecting text:
- [x] Slice image to given bounds of standard object
- [x] Rotate image so text is upright
- [x] Preprocess image to clean up before text detection
- [x] Text detection of character
- [x] Construct bounds for detected text
