### ISSUE TITLE
Emergent Object Detection

### ISSUE THREAD

**Issue by mat-px** [MissouriMRR/SUAS-2022#2]
emergent_in_frame.py

Detect a person engaged in an "activity" of interest:
-motion detection
-object detection (to find potential humans)
-human detection from objects found (shape-based, texture-based or motion-based features)

Object should be in the search area. Returns a bool.

*Maybe look into datasets that could help train to distinguish humans (score based)

![image](https://user-images.githubusercontent.com/25957968/137047642-cf73fb00-b8f2-40e7-b866-03cb5a144da1.png)

**Comment by mat-px** [comment]
https://medium.com/nanonets/how-i-built-a-self-flying-drone-to-track-people-in-under-50-lines-of-code-7485de7f828e

**Comment by mat-px** [comment]
https://github.com/LeonLok/Deep-SORT-YOLOv4

**Comment by mat-px** [comment]
https://medium.com/@luanaebio/detecting-people-with-yolo-and-opencv-5c1f9bc6a810

**Comment by fallscameron01** [comment]
**Ideas**

- Mad lib
- Take picture at last known location and prompt user to provide a description
- Some sort of machine learning model to identify
- Color detection at center of image
